### PR TITLE
Update resource-point-gathering.md

### PR DESCRIPTION
**Pull request by Citrona**
Wrong informations

### CODE REVIEW

**Comment by eeshvardasikcm** [comment]
You could be correct. Verifying percentage later. Going ahead and merging pull request for now.

**Comment by eeshvardasikcm** [comment]
Citrona, I checked most of the reading material available in RoK on my Android install. I don't see any real percentages listed. I remember researching on google. Someone said it was 5% and I believed them. It was helpful to receive your pull request👍. I'm going to remove the calculation and replace it with general language similar to what is used in game.

**Comment by Citrona** [comment]
image

Informations from customer support

**Comment by eeshvardasikcm** [comment]
Excellent! That's awesome! I'm going to favor your research over mine for now until I get more experience with that support channel.

**Comment by Citrona** [comment]
No problem I share the little knowledge I have about this game :)

**Pull request merged**
